const SUPABASE_URL='https://tfqzzhpehrkkxmrpwkas.supabase.co';
const SUPABASE_KEY='sb_publishable_UUrd8g8HyaqaUdegSZLbLg_1pY9y2Dy';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let clients=[],vehicles=[],history=[],selectedVehicle=null,vehiclePhotoFile=null,odometerFile=null,workPhotoFiles=[];
const photoUrlCache=new Map();

function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0);if(id==='clientsView')loadClients();if(id==='vehiclesView')loadVehicles();if(id==='historyView')loadHistory();if(id==='interventionView'){$('intDate').value=new Date().toISOString().slice(0,10);loadVehicles(false)}}
function setSessionUI(session){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));if(session){$('homeView').classList.add('active');$('bottomNav').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('userLabel').textContent=session.user.email;loadDashboard()}else{$('authView').classList.add('active');$('bottomNav').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('userLabel').textContent='Gestão simples de oficina'}}
async function init(){const {data:{session}}=await sb.auth.getSession();const recovery=location.hash.includes('type=recovery')||new URLSearchParams(location.search).get('recovery')==='1';if(recovery&&session)showResetView();else setSessionUI(session);sb.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')showResetView();else if(event!=='INITIAL_SESSION')setSessionUI(s)})}
async function auth(mode){const email=$('email').value.trim(),password=$('password').value,box=$('authMsg');box.innerHTML='';if(!email||password.length<6)return box.innerHTML='<div class="error">Preencha um email válido e uma palavra-passe com pelo menos 6 caracteres.</div>';const appUrl=location.origin+location.pathname;const res=mode==='signup'?await sb.auth.signUp({email,password,options:{emailRedirectTo:appUrl}}):await sb.auth.signInWithPassword({email,password});if(res.error)box.innerHTML='<div class="error">'+esc(res.error.message)+'</div>';else if(mode==='signup'&&!res.data.session)box.innerHTML='<div class="ok">Conta criada. Enviámos um email de confirmação. Verifique também o Spam.</div>'}
async function forgotPassword(){const email=$('email').value.trim(),box=$('authMsg');box.innerHTML='';if(!email)return box.innerHTML='<div class="error">Indique primeiro o seu email.</div>';const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname+'?recovery=1'});box.innerHTML=error?'<div class="error">'+esc(error.message)+'</div>':'<div class="ok">Enviámos uma ligação para definir uma nova palavra-passe. Verifique também o Spam.</div>'}
function showResetView(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('resetView').classList.add('active');$('bottomNav').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('userLabel').textContent='Recuperação de palavra-passe'}
async function updatePassword(){const p1=$('newPassword').value,p2=$('confirmPassword').value,box=$('resetMsg');if(p1.length<6)return box.innerHTML='<div class="error">A palavra-passe deve ter pelo menos 6 caracteres.</div>';if(p1!==p2)return box.innerHTML='<div class="error">As palavras-passe não coincidem.</div>';const {error}=await sb.auth.updateUser({password:p1});if(error)return box.innerHTML='<div class="error">'+esc(error.message)+'</div>';box.innerHTML='<div class="ok">✓ Palavra-passe alterada.</div>';history.replaceState({},document.title,location.pathname);setTimeout(async()=>setSessionUI((await sb.auth.getSession()).data.session),700)}
$('loginBtn').onclick=()=>auth('login');$('signupBtn').onclick=()=>auth('signup');$('forgotBtn').onclick=forgotPassword;$('updatePasswordBtn').onclick=updatePassword;$('logoutBtn').onclick=()=>sb.auth.signOut();

async function loadDashboard(){await Promise.all([loadClients(false),loadVehicles(false)]);$('countClients').textContent=clients.length;$('countVehicles').textContent=vehicles.length}
async function loadClients(render=true){const {data,error}=await sb.from('oficina_clientes').select('*').order('nome');if(!error)clients=data||[];fillClientSelect();if(render){await loadVehicles(false);renderClients()}}
function fillClientSelect(){if(!$('vehicleClient'))return;$('vehicleClient').innerHTML='<option value="">Selecione o cliente</option>'+clients.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join('')}
function renderClients(){const q=($('clientSearch').value||'').toLowerCase();const arr=clients.filter(c=>{const cv=vehicles.filter(v=>v.cliente_id===c.id);return (c.nome+' '+(c.telefone||'')+' '+(c.email||'')+' '+cv.map(v=>`${v.matricula} ${v.marca||''} ${v.modelo||''} ${v.cor||''}`).join(' ')).toLowerCase().includes(q)});$('clientList').innerHTML=arr.length?arr.map(c=>{const cv=vehicles.filter(v=>v.cliente_id===c.id);return `<div class="clientCard"><div class="clientTop"><div><strong style="font-size:20px">${esc(c.nome)}</strong><small class="muted" style="display:block;margin-top:4px">${esc(c.telefone||'Sem telefone')} · ${esc(c.email||'Sem email')}</small></div><button class="mini" onclick="editClient('${c.id}')">Editar</button></div><div class="clientVehicles"><strong>Viaturas (${cv.length})</strong>${cv.length?cv.map(v=>`<div class="clientVehicle">${v._fotoUrl?`<img src="${esc(v._fotoUrl)}" alt="${esc(v.matricula)}">`:'<div class="carPlaceholder">🚗</div>'}<div class="meta"><div class="plate">${esc(v.matricula)}</div><small class="muted">${esc(v.marca)} ${esc(v.modelo)}${v.cor?' · '+esc(v.cor):''}</small></div><button class="mini" onclick="openVehicleFromClient('${v.id}')">Abrir</button></div>`).join(''):'<div class="muted" style="padding:12px 0">Sem viaturas associadas.</div>'}<button class="btn secondary" onclick="newVehicleForClient('${c.id}')">＋ Adicionar viatura</button></div></div>`}).join(''):'<div class="empty">Ainda não existem clientes.</div>'}
function openClientForm(c=null){$('clientFormCard').classList.remove('hidden');$('clientFormTitle').textContent=c?'Editar cliente':'Novo cliente';$('clientId').value=c?.id||'';$('clientName').value=c?.nome||'';$('clientPhone').value=c?.telefone||'';$('clientEmail').value=c?.email||'';$('clientNif').value=c?.nif||'';$('clientNotes').value=c?.notas||'';$('clientName').focus()}
function closeClientForm(){$('clientFormCard').classList.add('hidden')}
function editClient(id){openClientForm(clients.find(c=>c.id===id))}
async function saveClient(){const nome=$('clientName').value.trim();if(!nome)return alert('Indique o nome do cliente.');const payload={nome,telefone:$('clientPhone').value.trim()||null,email:$('clientEmail').value.trim()||null,nif:$('clientNif').value.trim()||null,notas:$('clientNotes').value.trim()||null,atualizado_em:new Date().toISOString()},id=$('clientId').value;const res=id?await sb.from('oficina_clientes').update(payload).eq('id',id):await sb.from('oficina_clientes').insert(payload);if(res.error)return alert(res.error.message);closeClientForm();await loadClients();await loadDashboard()}

async function signedPhotoUrl(path){if(!path)return null;if(photoUrlCache.has(path))return photoUrlCache.get(path);const {data,error}=await sb.storage.from('oficina-fotos').createSignedUrl(path,3600);if(error)return null;photoUrlCache.set(path,data.signedUrl);return data.signedUrl}
async function loadVehicles(render=true){const {data,error}=await sb.from('oficina_viaturas').select('*, oficina_clientes(nome)').order('matricula');if(!error){vehicles=data||[];await Promise.all(vehicles.map(async v=>v._fotoUrl=await signedPhotoUrl(v.foto_caminho_storage)))}if(render)renderVehicles()}
function renderVehicles(){const q=($('vehicleSearch').value||'').toLowerCase();const arr=vehicles.filter(v=>(`${v.matricula} ${v.marca||''} ${v.modelo||''} ${v.cor||''} ${v.oficina_clientes?.nome||''}`).toLowerCase().includes(q));$('vehicleList').innerHTML=arr.length?arr.map(v=>`<div class="row vehicleCard">${v._fotoUrl?`<img class="vehicleThumb" src="${esc(v._fotoUrl)}" alt="${esc(v.matricula)}">`:'<div class="vehicleThumb carPlaceholder">🚗</div>'}<div class="vehicleInfo"><strong>${esc(v.matricula)}</strong><small>${esc(v.marca)} ${esc(v.modelo)}${v.cor?' · '+esc(v.cor):''}</small><small>${esc(v.oficina_clientes?.nome||'Sem cliente')}</small></div><button class="mini" onclick="editVehicle('${v.id}')">Editar</button></div>`).join(''):'<div class="empty">Ainda não existem viaturas.</div>'}
function setVehiclePhoto(file){if(!file)return;vehiclePhotoFile=file;$('vehiclePhotoPreview').innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Fotografia do carro">`;$('vehiclePhotoStatus').textContent='✓ Fotografia selecionada'}
$('vehiclePhotoCamera').onchange=e=>{setVehiclePhoto(e.target.files[0]);e.target.value=''};$('vehiclePhotoUpload').onchange=e=>{setVehiclePhoto(e.target.files[0]);e.target.value=''};
async function openVehicleForm(v=null,presetClientId=null){await loadClients(false);fillClientSelect();vehiclePhotoFile=null;$('vehicleFormCard').classList.remove('hidden');$('vehicleFormTitle').textContent=v?'Editar viatura':'Nova viatura';$('vehicleId').value=v?.id||'';$('vehiclePlate').value=v?.matricula||'';$('vehicleClient').value=v?.cliente_id||presetClientId||'';$('vehicleBrand').value=v?.marca||'';$('vehicleModel').value=v?.modelo||'';$('vehicleColor').value=v?.cor||'';$('vehicleYear').value=v?.ano||'';$('vehicleKm').value=v?.quilometragem_atual||'';$('vehicleVin').value=v?.vin||'';$('vehicleNotes').value=v?.notas||'';$('vehiclePhotoPreview').innerHTML=v?._fotoUrl?`<img src="${esc(v._fotoUrl)}" alt="Fotografia atual do carro">`:'';$('vehiclePhotoStatus').textContent=v?.foto_caminho_storage?'✓ Fotografia guardada':'';$('vehiclePlate').focus()}
function closeVehicleForm(){$('vehicleFormCard').classList.add('hidden');vehiclePhotoFile=null}
function editVehicle(id){openVehicleForm(vehicles.find(v=>v.id===id))}
function openVehicleFromClient(id){showView('vehiclesView');setTimeout(()=>editVehicle(id),80)}
function newVehicleForClient(clientId){showView('vehiclesView');setTimeout(()=>openVehicleForm(null,clientId),80)}
async function uploadVehiclePhoto(file,vehicleId){const {data:{user}}=await sb.auth.getUser(),ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/vehicles/${vehicleId}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('oficina-fotos').upload(path,file,{contentType:file.type||'image/jpeg'});if(error)throw error;return path}
async function saveVehicle(){const matricula=$('vehiclePlate').value.trim().toUpperCase(),cliente_id=$('vehicleClient').value,marca=$('vehicleBrand').value.trim(),modelo=$('vehicleModel').value.trim(),cor=$('vehicleColor').value.trim(),id=$('vehicleId').value,existing=id?vehicles.find(v=>v.id===id):null;if(!matricula||!cliente_id||!marca||!modelo||!cor)return alert('Preencha matrícula, cliente, marca, modelo e cor.');if(!vehiclePhotoFile&&!existing?.foto_caminho_storage)return alert('Adicione uma fotografia do carro.');const payload={matricula,cliente_id,marca,modelo,cor,ano:+$('vehicleYear').value||null,quilometragem_atual:+$('vehicleKm').value||null,vin:$('vehicleVin').value.trim()||null,notas:$('vehicleNotes').value.trim()||null,atualizado_em:new Date().toISOString()};try{let saved;if(id){const r=await sb.from('oficina_viaturas').update(payload).eq('id',id).select().single();if(r.error)throw r.error;saved=r.data}else{const r=await sb.from('oficina_viaturas').insert(payload).select().single();if(r.error)throw r.error;saved=r.data}if(vehiclePhotoFile){const path=await uploadVehiclePhoto(vehiclePhotoFile,saved.id),r=await sb.from('oficina_viaturas').update({foto_caminho_storage:path,atualizado_em:new Date().toISOString()}).eq('id',saved.id);if(r.error)throw r.error}closeVehicleForm();await loadVehicles();await loadDashboard()}catch(err){alert('Não foi possível guardar a viatura: '+(err.message||err))}}

async function findVehicleByPlate(){const p=$('intPlate').value.trim().toUpperCase();if(!p)return;await loadVehicles(false);selectedVehicle=vehicles.find(v=>v.matricula.toUpperCase()===p)||null;if(!selectedVehicle)return $('vehicleMatch').innerHTML='<div class="error">Matrícula não encontrada. Crie primeiro a viatura.</div>';$('vehicleMatch').innerHTML=`<div class="ok vehicleCard">${selectedVehicle._fotoUrl?`<img class="vehicleThumb" src="${esc(selectedVehicle._fotoUrl)}">`:''}<div><strong>${esc(selectedVehicle.matricula)}</strong><div>${esc(selectedVehicle.marca)} ${esc(selectedVehicle.modelo)}${selectedVehicle.cor?' · '+esc(selectedVehicle.cor):''}</div></div></div>`;$('intKm').value=selectedVehicle.quilometragem_atual||''}
function addPart(){const d=document.createElement('div');d.className='part';d.innerHTML='<label>Nome da peça</label><input class="partName" placeholder="Ex.: Filtro de óleo"><div class="grid2"><div><label>Referência</label><input class="partRef"></div><div><label>Quantidade</label><input class="partQty" type="number" step="0.01" value="1"></div></div><button class="btn danger" onclick="this.parentElement.remove()">Remover peça</button>';$('parts').appendChild(d)}
function setOdometerFile(file){if(!file)return;odometerFile=file;$('odoPreview').innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Conta-quilómetros">`}
function addWorkFiles(files){workPhotoFiles.push(...files);$('workPreview').innerHTML=workPhotoFiles.map(f=>`<img src="${URL.createObjectURL(f)}" alt="Fotografia do trabalho">`).join('')}
$('odoCamera').onchange=e=>{setOdometerFile(e.target.files[0]);e.target.value=''};$('odoUpload').onchange=e=>{setOdometerFile(e.target.files[0]);e.target.value=''};$('workCamera').onchange=e=>{if(e.target.files[0])addWorkFiles([e.target.files[0]]);e.target.value=''};$('workUpload').onchange=e=>{addWorkFiles([...e.target.files]);e.target.value=''};
async function uploadInterventionPhoto(file,interventionId,type){const {data:{user}}=await sb.auth.getUser(),ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${user.id}/interventions/${interventionId}/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('oficina-fotos').upload(path,file,{contentType:file.type||'image/jpeg'});if(up.error)throw up.error;const db=await sb.from('oficina_fotografias').insert({intervencao_id:interventionId,tipo:type,caminho_storage:path});if(db.error)throw db.error}
async function saveIntervention(){const btn=$('saveInterventionBtn'),msg=$('intMsg');msg.innerHTML='';if(!selectedVehicle||selectedVehicle.matricula!==$('intPlate').value.trim().toUpperCase()){await findVehicleByPlate();if(!selectedVehicle)return}const km=+$('intKm').value,tipo=$('serviceType').value.trim();if(!km||!tipo)return msg.innerHTML='<div class="error">Preencha os quilómetros e o tipo de serviço.</div>';if(!odometerFile)return msg.innerHTML='<div class="error">A fotografia do conta-quilómetros é obrigatória.</div>';btn.disabled=true;btn.textContent='A guardar…';try{const r=await sb.from('oficina_intervencoes').insert({viatura_id:selectedVehicle.id,data:$('intDate').value||new Date().toISOString().slice(0,10),quilometragem:km,tipo_servico:tipo,descricao:$('workDesc').value.trim()||null,notas:$('intNotes').value.trim()||null}).select().single();if(r.error)throw r.error;for(const n of document.querySelectorAll('.part')){const nome=n.querySelector('.partName').value.trim();if(nome){const x=await sb.from('oficina_pecas').insert({intervencao_id:r.data.id,nome,referencia:n.querySelector('.partRef').value.trim()||null,quantidade:+n.querySelector('.partQty').value||1});if(x.error)throw x.error}}await uploadInterventionPhoto(odometerFile,r.data.id,'conta_quilometros');for(const f of workPhotoFiles)await uploadInterventionPhoto(f,r.data.id,'trabalho');await sb.from('oficina_viaturas').update({quilometragem_atual:km,atualizado_em:new Date().toISOString()}).eq('id',selectedVehicle.id);msg.innerHTML='<div class="ok">✓ Intervenção guardada com sucesso.</div>';resetIntervention();await loadDashboard()}catch(err){msg.innerHTML='<div class="error">Não foi possível guardar: '+esc(err.message||err)+'</div>'}finally{btn.disabled=false;btn.textContent='✓ Terminar e guardar'}}
function resetIntervention(){selectedVehicle=null;odometerFile=null;workPhotoFiles=[];['intPlate','intKm','serviceType','workDesc','intNotes'].forEach(id=>$(id).value='');$('parts').innerHTML='';$('vehicleMatch').innerHTML='';$('odoPreview').innerHTML='';$('workPreview').innerHTML='';$('intDate').value=new Date().toISOString().slice(0,10)}

async function loadHistory(){const {data,error}=await sb.from('oficina_intervencoes').select('*, oficina_viaturas(matricula,marca,modelo,cor,oficina_clientes(nome)), oficina_pecas(nome,referencia,quantidade)').order('data',{ascending:false}).order('criado_em',{ascending:false});if(!error)history=data||[];renderHistory()}
function renderHistory(){const q=($('historySearch').value||'').toLowerCase(),arr=history.filter(h=>((h.oficina_viaturas?.matricula||'')+' '+h.tipo_servico+' '+(h.descricao||'')).toLowerCase().includes(q));$('historyList').innerHTML=arr.length?arr.map(h=>`<div class="card"><div class="sectionHead"><div><span class="pill">${esc(h.data)}</span><h3 style="margin-top:8px">${esc(h.oficina_viaturas?.matricula||'')}</h3></div><strong>${Number(h.quilometragem).toLocaleString('pt-PT')} km</strong></div><strong>${esc(h.tipo_servico)}</strong><p class="muted">${esc(h.descricao||'Sem descrição')}</p>${h.oficina_pecas?.length?`<p><strong>Peças:</strong> ${h.oficina_pecas.map(p=>esc(p.nome)).join(', ')}</p>`:''}<small class="muted">${esc(h.oficina_viaturas?.marca||'')} ${esc(h.oficina_viaturas?.modelo||'')}${h.oficina_viaturas?.cor?' · '+esc(h.oficina_viaturas.cor):''} · ${esc(h.oficina_viaturas?.oficina_clientes?.nome||'Sem cliente')}</small></div>`).join(''):'<div class="empty">Ainda não existem intervenções.</div>'}

init();